"""
Domain entities representing core business objects.

Pure Python dataclasses without framework dependencies.
"""

from dataclasses import dataclass
from datetime import datetime

@dataclass
class EvaluationEntity:
    """Position evaluation from chess engine."""
    fen: str
    type: str
    value: int
    move_played: str = ""

@dataclass
class GameEntity:
    """Chess game domain entity."""
    pgn: str
    white: str
    black: str
    result: str
    id: int | None = None
    created_at: datetime | None = None

@dataclass
class Mistake:
    """Represents a mistake in a chess game."""
    move_number: int
    player: str          # "white" | "black"
    fen_before: str
    fen_after: str
    eval_before: int     # centipawns
    eval_after: int
    move_played: str

@dataclass
class Explanation:
    """Represents an explanation for a mistake."""
    mistake: Mistake
    text: str            # generated by Claude
    best_move: str       # engine's top choice