from typing import Protocol

from app.domain.entities import EvaluationEntity, GameEntity

class GameRepositoryPort(Protocol):
    def add_game(self, game: GameEntity) -> GameEntity: ...
    def get_games(self) -> list[GameEntity]: ...
    def get_game_by_id(self, game_id: int) -> GameEntity | None: ...

class ChessEnginePort(Protocol):
    def analyze(self, game: GameEntity) -> list[EvaluationEntity]: ...