from asyncio import Protocol

from app.domain.entities import EvaluationEntityResponse

class GameRepositoryPort(Protocol):
    def add_game(self, game) -> None: ...
    def get_games(self) -> list: ...
    def get_game_by_id(self, game_id: int): ...

class ChessEnginePort(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def analyze(self, game) -> list[EvaluationEntityResponse]: ...