"""
Port interfaces for hexagonal architecture.

Defines contracts for adapters (repository and chess engine).
"""
from datetime import date
from typing import Protocol
from app.domain.entities import Drill, EvaluationEntity, Explanation, GameEntity, Mistake

class GameRepositoryPort(Protocol):
    """Port for game persistence operations."""
    def add_game(self, game: GameEntity) -> GameEntity: ...
    def get_games(self) -> list[GameEntity]: ...
    def get_game_by_id(self, game_id: int) -> GameEntity | None: ...

class CoachingPort(Protocol):
    # Port for coaching operations, such as explaining mistakes in a game.
    def explain(
        self, game: GameEntity, mistakes: list[Mistake]
    ) -> list[Explanation]: ...

class ChessEnginePort(Protocol):
    """Port for chess engine analysis operations."""
    def analyze(self, game: GameEntity) -> list[EvaluationEntity]: ...
    def get_best_move(self, fen: str) -> str: ...
    def evaluate_fen(self, fen: str) -> EvaluationEntity: ...

class DrillRepositoryPort(Protocol):
    """Port for drill persistence operations."""
    def add_drill(self, drill: Drill) -> Drill: ...
    def get_due_drills(self, as_of: date) -> list[Drill]: ...
    def get_drill_by_id(self, drill_id: int) -> Drill | None: ...
    def update_drill(self, drill: Drill) -> Drill: ...